"""
Django settings for aghub project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
# import sentry_sdk

# sentry_sdk.init(
#     dsn="https://8a250e1c9574ffe397492f9b5d96450c@o4504838454640640.ingest.sentry.io/4506144901824512",
#     # Set traces_sample_rate to 1.0 to capture 100%
#     # of transactions for performance monitoring.
#     traces_sample_rate=1.0,
#     # Set profiles_sample_rate to 1.0 to profile 100%
#     # of sampled transactions.
#     # We recommend adjusting this value in production.
#     profiles_sample_rate=1.0,
# )


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&%hs^a(jsayuipj908ewhfsdjkb@#56f(3_*pbqw#co^@k&ysa4f*#@8*n!f8%!ej_#!u)zwus'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True #True

ALLOWED_HOSTS = [
    'easeusinfo.us-east-1.log.aliyuncs.com',
    '.agcbarnawa.online',
    '127.0.0.1',
    '.localhost',
]


# Application definition

INSTALLED_APPS = [
    'hub',
    'filebrowser',
    'grappelli',
#    'wagtail.contrib.forms',
#    'wagtail.contrib.modeladmin',
#    'wagtail.contrib.sitemaps',
#    'wagtail.contrib.routable_page',
#    'wagtail.contrib.table_block',
#    'wagtail.contrib.redirects',
#    'wagtail.embeds',
#    'wagtail.sites',
#    'wagtail.users',
#    'wagtail.snippets',
    # 'wagtail.blocks',
#    'wagtail.rich_text',
#    'wagtail.documents',
#    'wagtail.images',
#    'wagtail.search',
#    'wagtail.admin',
#    'wagtail',

 #   'modelcluster',
  #  'taggit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.humanize',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'wagtail.contrib.redirects.middleware.RedirectMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aghub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aghub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#  Filebrowser
FILEBROWSER_DIRECTORY = os.path.join(BASE_DIR, 'files/')
FILEBROWSER_MAX_UPLOAD_SIZE = 1073741824

# Set the maximum upload size to 1 GB (in bytes)
DATA_UPLOAD_MAX_MEMORY_SIZE = 1073741824  # 1 GB in bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 1073741824  # 1 GB in bytes


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

TIME_ZONE = 'Africa/Lagos'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = os.path.join(BASE_DIR, 'files')
MEDIA_URL = '/files/'

#  Grappelli Admin Customizations
GRAPPELLI_ADMIN_TITLE = 'AGC Barnawa'

#WAGTAILADMIN_BASE_URL = '/'
#WAGTAIL_SITE_NAME = "AG Hub"

